# Set up Jeykll theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Customize Site
title: [The title of your site]
description: [A short description of your site's purpose]
